### ISSUE TITLE
Support English as an output language

### ISSUE THREAD

**Issue by turian** [tcapelle/gpt_translate#2]
It's not yet supported to translate *into* English. Please add this feature

**Comment by tcapelle** [comment]
You could actually do that, just add the missing dict here: https://github.com/tcapelle/gpt_translate/blob/main/gpt_translate/roles.py

**Comment by tcapelle** [comment]
I simplified the logic a lot and make it work with config files, now you can add the english dict and prompt and you should be able to use it!
